name = "family-expenses"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."


[[d1_databases]]
binding = "DB"
database_name = "family-expenses"
database_id = "cc4716b1-e80b-4239-9584-0a72c46cf376"
migrations_dir = "migrations"
